import "./globals.css";
import { StateProvider } from "@/redux/StateProvider";
import { Inter } from "next/font/google";
import Footer from "@/components/global/Footer";
import FloatingNavbar from "@/components/global/FloatingNavbar";
import ThemeSwitcher from "@/components/global/ThemeSwitcher";
import { ReactNode } from "react";
import ThemeStateProvider from "@/components/global/ThemeStateProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <StateProvider>
        <body className={`${inter.className} relative bg-white dark:bg-black`}>
          <ThemeStateProvider>
            <ThemeSwitcher />
            <FloatingNavbar />
            {children}
            <Footer />
          </ThemeStateProvider>
        </body>
      </StateProvider>
    </html>
  );
}
