import { StateProvider } from "@/redux/StateProvider";
import "./globals.css";
import { Inter } from "next/font/google";
import Footer from "@/components/global/Footer";
import FloatingNavbar from "@/components/global/FloatingNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} relative`}>
        <FloatingNavbar />
        <StateProvider>{children}</StateProvider>
        <Footer />
      </body>
    </html>
  );
}
